"""Top-level command-line entry point for ReproEval."""

from __future__ import annotations

import argparse
import asyncio
from collections.abc import Sequence
from pathlib import Path

from hy3_reproscope_mcp.errors import ReproScopeError

from . import __version__
from .agreement import analyze_annotation_agreement
from .annotation_packet import finalize_annotation_packet, prepare_annotation_packet
from .annotations import validate_annotation_bundles
from .benchmark import BenchmarkMode, run_dataset_benchmark
from .consensus import finalize_annotation_consensus
from .dataset import replay_mutation_manifest, validate_dataset_manifest
from .errors import EvaluationInputError
from .evaluator import evaluate_case_file, evaluate_case_file_hybrid
from .freeze import create_dataset_freeze, verify_dataset_freeze
from .judge import write_judge_record
from .judge_batch import generate_dataset_judge_records
from .judge_experiment import run_judge_experiment
from .p0_dataset import materialize_p0_dataset
from .p1_transfer_dataset import materialize_p1_transfer_dataset
from .pairwise import compare_case_files, write_pairwise_bundle
from .results_export import export_benchmark_results
from .stability import analyze_benchmark_stability


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hy3-reproeval",
        description="Generate and evaluate evidence-grounded research reports with Hy3.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    subparsers = parser.add_subparsers(dest="command")
    subparsers.add_parser("serve-mcp", help="Run the migrated ReproScope MCP server over stdio.")
    evaluate_parser = subparsers.add_parser(
        "evaluate-report",
        help="Run deterministic seven-dimension evaluation from a case manifest.",
    )
    evaluate_parser.add_argument("--case", required=True, type=Path, help="Path to an evaluation case JSON file.")
    evaluate_parser.add_argument("--output", type=Path, help="Optional path for the evaluation result JSON.")
    evaluate_parser.add_argument(
        "--judge",
        choices=("none", "online", "replay"),
        default="none",
        help="Semantic Judge mode. The default runs deterministic validators only.",
    )
    evaluate_parser.add_argument(
        "--judge-record",
        type=Path,
        help="Write an online Judge record, or read this record in replay mode.",
    )
    compare_parser = subparsers.add_parser(
        "compare-reports",
        help="Blindly compare two reports under one evaluation contract with repeated Hy3 Judge trials.",
    )
    compare_parser.add_argument("--left-case", required=True, type=Path)
    compare_parser.add_argument("--right-case", required=True, type=Path)
    compare_parser.add_argument("--comparison-id", required=True)
    compare_parser.add_argument("--repeats", type=int, default=3)
    compare_parser.add_argument("--judge", choices=("online", "replay"), required=True)
    compare_parser.add_argument(
        "--judge-record",
        type=Path,
        help="Write an online pairwise Judge bundle, or read this bundle in replay mode.",
    )
    compare_parser.add_argument("--output", type=Path, help="Optional path for the comparison result JSON.")
    dataset_parser = subparsers.add_parser(
        "validate-dataset",
        help="Validate dataset tiers, mutations, group isolation, hashes, and expected deterministic errors.",
    )
    dataset_parser.add_argument("--manifest", required=True, type=Path)
    dataset_parser.add_argument("--output", type=Path, help="Optional path for the validation result JSON.")
    p0_parser = subparsers.add_parser(
        "build-p0-dataset",
        help="Materialize or byte-verify the canonical synthetic P0 Dataset candidate.",
    )
    p0_parser.add_argument("--output", required=True, type=Path)
    p0_parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the existing inventory against canonical generated bytes without writing.",
    )
    p1_parser = subparsers.add_parser(
        "build-p1-transfer-dataset",
        help="Materialize or byte-verify the canonical synthetic P1 transfer Dataset.",
    )
    p1_parser.add_argument("--output", required=True, type=Path)
    p1_parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the existing inventory against canonical generated bytes without writing.",
    )
    freeze_parser = subparsers.add_parser(
        "freeze-dataset",
        help="Create a tamper-evident inventory of every registered Dataset input.",
    )
    freeze_parser.add_argument("--manifest", required=True, type=Path)
    freeze_parser.add_argument("--output", required=True, type=Path)
    freeze_parser.add_argument(
        "--require-p0-ready",
        action="store_true",
        help="Reject a Dataset below the declared P0 group, split, or adversarial targets.",
    )
    verify_freeze_parser = subparsers.add_parser(
        "verify-dataset-freeze",
        help="Verify a Dataset Freeze against its self-digest and current registered inputs.",
    )
    verify_freeze_parser.add_argument("--freeze", required=True, type=Path)
    verify_freeze_parser.add_argument("--manifest", required=True, type=Path)
    verify_freeze_parser.add_argument("--output", type=Path)
    mutation_parser = subparsers.add_parser(
        "replay-mutation",
        help="Deterministically replay and verify one literal Mutation Manifest.",
    )
    mutation_parser.add_argument("--manifest", required=True, type=Path)
    mutation_parser.add_argument("--root", type=Path, help="Dataset root; defaults to the manifest directory.")
    mutation_parser.add_argument(
        "--write", action="store_true", help="Write the verified output instead of checking it."
    )
    benchmark_parser = subparsers.add_parser(
        "benchmark-dataset",
        help="Batch-evaluate registered report tiers and compute group-isolated ranking metrics.",
    )
    benchmark_parser.add_argument("--manifest", required=True, type=Path)
    benchmark_parser.add_argument(
        "--mode",
        choices=tuple(BenchmarkMode),
        default=BenchmarkMode.DETERMINISTIC,
        type=BenchmarkMode,
        help="Use deterministic validators only, or registered Judge replay records.",
    )
    benchmark_parser.add_argument(
        "--judge-index",
        type=Path,
        help="Optional complete Judge Record index generated by generate-judge-records.",
    )
    benchmark_parser.add_argument(
        "--dataset-freeze",
        type=Path,
        help="Optional verified Dataset Freeze binding for this benchmark.",
    )
    benchmark_parser.add_argument("--output", type=Path, help="Optional path for the benchmark result JSON.")
    stability_parser = subparsers.add_parser(
        "analyze-benchmark-stability",
        help="Analyze repeated replay Benchmarks bound to one Dataset Freeze.",
    )
    stability_parser.add_argument(
        "--benchmark",
        required=True,
        action="append",
        type=Path,
        help="Dataset Benchmark result JSON; repeat for each independent Judge run.",
    )
    stability_parser.add_argument("--output", type=Path, help="Optional stability result JSON path.")
    export_parser = subparsers.add_parser(
        "export-benchmark-results",
        help="Export verified repeated Benchmark results as Markdown and CSV review artifacts.",
    )
    export_parser.add_argument(
        "--benchmark",
        required=True,
        action="append",
        type=Path,
        help="Dataset Benchmark result JSON; repeat for every run represented by the Stability result.",
    )
    export_parser.add_argument("--stability", required=True, type=Path)
    export_parser.add_argument("--output-dir", required=True, type=Path)
    generate_parser = subparsers.add_parser(
        "generate-judge-records",
        help="Generate one resumable online Hy3 Judge Record per dataset report.",
    )
    generate_parser.add_argument("--manifest", required=True, type=Path)
    generate_parser.add_argument("--output-dir", required=True, type=Path)
    generate_parser.add_argument("--model", help="Optional model override; defaults to HY3_MODEL.")
    generate_parser.add_argument("--provider", help="Optional provider provenance override.")
    generate_parser.add_argument(
        "--dataset-freeze",
        type=Path,
        help="Optional verified Dataset Freeze binding for generated Judge Records.",
    )
    generate_parser.add_argument(
        "--resume",
        action="store_true",
        help="Verify and reuse existing records from an interrupted run.",
    )
    experiment_parser = subparsers.add_parser(
        "run-judge-experiment",
        help="Run or resume a frozen repeated-Judge Benchmark and review export.",
    )
    experiment_parser.add_argument("--manifest", required=True, type=Path)
    experiment_parser.add_argument("--output-dir", required=True, type=Path)
    experiment_parser.add_argument("--runs", type=int, default=3)
    experiment_parser.add_argument("--model", help="Optional model override; defaults to HY3_MODEL.")
    experiment_parser.add_argument("--provider", help="Optional provider provenance override.")
    experiment_parser.add_argument(
        "--resume",
        action="store_true",
        help="Verify and resume the existing experiment directory.",
    )
    prepare_packet_parser = subparsers.add_parser(
        "prepare-annotation-packet",
        help="Create one randomized, label-blind work packet for an independent human annotator.",
    )
    prepare_packet_parser.add_argument("--manifest", required=True, type=Path)
    prepare_packet_parser.add_argument("--dataset-freeze", required=True, type=Path)
    prepare_packet_parser.add_argument("--output-dir", required=True, type=Path)
    prepare_packet_parser.add_argument("--assignment-id", required=True)
    prepare_packet_parser.add_argument("--annotator-id", required=True)
    prepare_packet_parser.add_argument("--bundle-id", required=True)
    finalize_packet_parser = subparsers.add_parser(
        "finalize-annotation-packet",
        help="Verify a completed blind packet and emit a strict human Annotation Bundle.",
    )
    finalize_packet_parser.add_argument("--manifest", required=True, type=Path)
    finalize_packet_parser.add_argument("--dataset-freeze", required=True, type=Path)
    finalize_packet_parser.add_argument("--packet-dir", required=True, type=Path)
    finalize_packet_parser.add_argument("--output", required=True, type=Path)
    annotations_parser = subparsers.add_parser(
        "validate-annotations",
        help="Validate de-identified human or synthetic annotation bundles against a dataset.",
    )
    annotations_parser.add_argument("--manifest", required=True, type=Path)
    annotations_parser.add_argument(
        "--bundle",
        required=True,
        action="append",
        type=Path,
        help="Annotation Bundle JSON; repeat for multiple independent annotators.",
    )
    annotations_parser.add_argument("--output", type=Path, help="Optional validation result JSON path.")
    annotations_parser.add_argument(
        "--dataset-freeze",
        type=Path,
        help="Optional verified Dataset Freeze required by every annotation Bundle.",
    )
    agreement_parser = subparsers.add_parser(
        "analyze-annotations",
        help="Compute human agreement, adjudication items, and optional system-human metrics.",
    )
    agreement_parser.add_argument("--manifest", required=True, type=Path)
    agreement_parser.add_argument(
        "--bundle",
        required=True,
        action="append",
        type=Path,
        help="Annotation Bundle JSON; repeat for each independent annotator.",
    )
    agreement_parser.add_argument(
        "--benchmark-result",
        type=Path,
        help="Optional bound Dataset Benchmark JSON for system-human comparison.",
    )
    agreement_parser.add_argument("--output", type=Path, help="Optional agreement result JSON path.")
    agreement_parser.add_argument(
        "--dataset-freeze",
        type=Path,
        help="Optional verified Dataset Freeze binding for agreement analysis.",
    )
    consensus_parser = subparsers.add_parser(
        "finalize-annotations",
        help="Aggregate independent labels and resolve queued disputes through parent-bound adjudication Bundles.",
    )
    consensus_parser.add_argument("--manifest", required=True, type=Path)
    consensus_parser.add_argument(
        "--bundle",
        required=True,
        action="append",
        type=Path,
        help="Independent, repeat, or adjudication Bundle JSON; repeat for the complete lineage set.",
    )
    consensus_parser.add_argument("--output", type=Path, help="Optional consensus result JSON path.")
    consensus_parser.add_argument(
        "--dataset-freeze",
        type=Path,
        help="Optional verified Dataset Freeze binding for consensus finalization.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.command == "serve-mcp":
        from hy3_reproscope_mcp.server import main as run_server

        run_server()
        return 0
    if args.command == "evaluate-report":
        try:
            if args.judge == "none":
                if args.judge_record is not None:
                    parser.error("--judge-record requires --judge online or --judge replay")
                result = evaluate_case_file(args.case)
            elif args.judge == "replay":
                if args.judge_record is None:
                    parser.error("--judge replay requires --judge-record")
                result, _ = asyncio.run(evaluate_case_file_hybrid(args.case, judge_replay_path=args.judge_record))
            else:
                result, judge_record = asyncio.run(evaluate_case_file_hybrid(args.case))
                if args.judge_record is not None:
                    write_judge_record(args.judge_record, judge_record)
        except (EvaluationInputError, ReproScopeError) as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_text(rendered, encoding="utf-8")
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "validate-dataset":
        try:
            result = validate_dataset_manifest(args.manifest)
        except EvaluationInputError as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_text(rendered, encoding="utf-8")
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "build-p0-dataset":
        try:
            result = materialize_p0_dataset(args.output, check=args.check)
        except EvaluationInputError as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "build-p1-transfer-dataset":
        try:
            result = materialize_p1_transfer_dataset(args.output, check=args.check)
        except EvaluationInputError as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "freeze-dataset":
        try:
            result = create_dataset_freeze(
                args.manifest,
                require_p0_ready=args.require_p0_ready,
            )
        except EvaluationInputError as exc:
            parser.error(str(exc))
        output_path = args.output.expanduser().resolve()
        if not output_path.parent.is_dir():
            parser.error(f"output directory does not exist: {output_path.parent}")
        output_path.write_bytes((result.model_dump_json(indent=2) + "\n").encode("utf-8"))
        print(output_path.as_posix())
        return 0
    if args.command == "verify-dataset-freeze":
        try:
            result = verify_dataset_freeze(args.freeze, args.manifest)
        except EvaluationInputError as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_bytes(rendered.encode("utf-8"))
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "replay-mutation":
        try:
            result = replay_mutation_manifest(
                args.manifest,
                root=args.root,
                write=args.write,
            )
        except EvaluationInputError as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "benchmark-dataset":
        try:
            result = asyncio.run(
                run_dataset_benchmark(
                    args.manifest,
                    mode=args.mode,
                    judge_index_path=args.judge_index,
                    dataset_freeze_path=args.dataset_freeze,
                )
            )
        except (EvaluationInputError, ReproScopeError) as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_text(rendered, encoding="utf-8")
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "analyze-benchmark-stability":
        try:
            result = analyze_benchmark_stability(args.benchmark)
        except EvaluationInputError as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_bytes(rendered.encode("utf-8"))
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "export-benchmark-results":
        try:
            result = export_benchmark_results(args.benchmark, args.stability, args.output_dir)
        except EvaluationInputError as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "generate-judge-records":
        try:
            result = asyncio.run(
                generate_dataset_judge_records(
                    args.manifest,
                    args.output_dir,
                    model=args.model,
                    provider=args.provider,
                    resume=args.resume,
                    dataset_freeze_path=args.dataset_freeze,
                )
            )
        except (EvaluationInputError, ReproScopeError) as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "run-judge-experiment":
        try:
            result = asyncio.run(
                run_judge_experiment(
                    args.manifest,
                    args.output_dir,
                    runs=args.runs,
                    model=args.model,
                    provider=args.provider,
                    resume=args.resume,
                )
            )
        except (EvaluationInputError, ReproScopeError) as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "prepare-annotation-packet":
        try:
            result = prepare_annotation_packet(
                args.manifest,
                args.dataset_freeze,
                args.output_dir,
                assignment_id=args.assignment_id,
                annotator_id=args.annotator_id,
                annotation_bundle_id=args.bundle_id,
            )
        except EvaluationInputError as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "finalize-annotation-packet":
        try:
            result = finalize_annotation_packet(
                args.manifest,
                args.dataset_freeze,
                args.packet_dir,
                args.output,
            )
        except EvaluationInputError as exc:
            parser.error(str(exc))
        print(result.model_dump_json(indent=2))
        return 0
    if args.command == "validate-annotations":
        try:
            result = validate_annotation_bundles(
                args.manifest,
                args.bundle,
                dataset_freeze_path=args.dataset_freeze,
            )
        except EvaluationInputError as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_bytes(rendered.encode("utf-8"))
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "analyze-annotations":
        try:
            result = analyze_annotation_agreement(
                args.manifest,
                args.bundle,
                benchmark_result_path=args.benchmark_result,
                dataset_freeze_path=args.dataset_freeze,
            )
        except EvaluationInputError as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_bytes(rendered.encode("utf-8"))
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "finalize-annotations":
        try:
            result = finalize_annotation_consensus(
                args.manifest,
                args.bundle,
                dataset_freeze_path=args.dataset_freeze,
            )
        except EvaluationInputError as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_bytes(rendered.encode("utf-8"))
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    if args.command == "compare-reports":
        if args.judge == "replay" and args.judge_record is None:
            parser.error("--judge replay requires --judge-record")
        try:
            result, bundle = asyncio.run(
                compare_case_files(
                    args.left_case,
                    args.right_case,
                    comparison_id=args.comparison_id,
                    repeats=args.repeats,
                    judge_replay_path=args.judge_record if args.judge == "replay" else None,
                )
            )
            if args.judge == "online" and args.judge_record is not None:
                write_pairwise_bundle(args.judge_record, bundle)
        except (EvaluationInputError, ReproScopeError) as exc:
            parser.error(str(exc))
        rendered = result.model_dump_json(indent=2) + "\n"
        if args.output is not None:
            output_path = args.output.expanduser().resolve()
            if not output_path.parent.is_dir():
                parser.error(f"output directory does not exist: {output_path.parent}")
            output_path.write_text(rendered, encoding="utf-8")
            print(output_path.as_posix())
        else:
            print(rendered, end="")
        return 0
    parser.print_help()
    return 0
